### ISSUE TITLE
I only have 1 proyect in C# but it says that it's my top language of the year?

### ISSUE THREAD

**Issue by Ingrid-E** [remotion-dev/github-unwrapped-2022#11]
I have a lot of proyects in Javascript but it still put C# as my top and i don't even know what is shaderlab

**Comment by JonnyBurger** [comment]
Sorry the top languages did not turn out well! They can indeed be inaccurate because it looks for the languages most used in the repositories that you contributed to, not the language of the contribution itself.

ShaderLab is for example used in the `proyecto-videojuegos` repository.
We'll consider whether we can improve that next year!
