### ISSUE TITLE
Shows a language I've not used on GitHub

### ISSUE THREAD

**Issue by tolik518** [remotion-dev/github-unwrapped-2022#20]
I don't know how this happens, but the generated video shows Java in the second place of my languages,
but I don't have any repos where I used Java on GitHub.

![Screenshot from 2022-12-21 16-59-33](https://user-images.githubusercontent.com/3026792/208948393-42a6b713-484a-4607-9482-7e4de27635c0.png)

Here is a link to my unwrapped so you can reassure yourself: https://www.githubunwrapped.com/tolik518

**Comment by GOTAM672** [comment]
Yes, I also have same problem .

**Comment by BoseSj** [comment]
It happened to me too. But then I found out, the major repos I have contributed to are using those languages. Maybe i m getting this wrong, **Maintainers** could best tell how it deals with the stats.

**Comment by tolik518** [comment]
> It happened to me too. But then I found out, the major repos I have contributed to are using those languages. Maybe i m getting this wrong, **Maintainers** could best tell how it deals with the stats.

I guess that would make sense that it's handled that way, but it would be a bad metric. 
If contributed a line of Bash to a huge Java repo, it would say that Java is one of my top languages.

**Comment by muescha** [comment]
also if i made changes only to a doc (for example typos) then it also count the repo language as my language 

would be nice to have a tweak section where i can see some of my languages used and i can uncheck repos/language to not count into the video

**Comment by JonnyBurger** [comment]
It is all true, we have an explainer here how the top languages are calculated: https://www.githubunwrapped.com/about

I think there is no scientifically correct way to calculate the top languages exactly using the GitHub API, since you can only get the languages of the repositories you contributed to. We already use weights so that those repositories with less contributions count less.

We could change the weights which would fix it for some people but break it for others.
I also think it is more fun if the UI is simple and there aren't any settings and toggles.

By the way, about 24h ago we fixed the algorithm a bit by toning down outliers. I have reset all your statistics, so see if it has been improved!
